# Site settings
title: "Minibooks"
author: "David Mace"
description: ""
keywords: "asdgfkgasdkhfgalkjsdhfjlk"

baseurl: ""
url: "http://hugosereno.eu"

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: :title/
